table ab_test_results
	lineageTag: 445bbc74-070f-49b4-b4d9-558188f08462

	measure 'Significant (95%)' = IF(MAX(ab_test_results[Significant at 95%]) = 1, "Yes", "No")
		lineageTag: 4ee6b566-194c-4f54-859d-29b3d0aa1952

	measure 'Significant (95%) with p' = IF(MAX(ab_test_results[Significant at 95%]) = 1, "Yes", "No") & " (p = " & FORMAT(MAX(ab_test_results[p-value]), "0.000") & ")"
		lineageTag: 5a94d382-caa3-4c02-8fa3-32b7753b1ac8

	column Test
		dataType: string
		lineageTag: e4b796c2-6185-4a3c-8349-1976d13c0972
		summarizeBy: none
		sourceColumn: ab_test_name

		annotation SummarizationSetBy = Automatic

	column Variant
		dataType: string
		lineageTag: d2f39a52-e8fe-43f1-bff7-ce1d0d091dad
		summarizeBy: none
		sourceColumn: variant

		annotation SummarizationSetBy = Automatic

	column Clicks
		dataType: int64
		formatString: 0
		lineageTag: aab69d6a-50d1-49c2-86e1-8c9f26f57204
		summarizeBy: sum
		sourceColumn: clicks

		annotation SummarizationSetBy = Automatic

	column Signups
		dataType: int64
		formatString: 0
		lineageTag: 7731b131-fde2-4121-a433-b052777ad79b
		summarizeBy: sum
		sourceColumn: registros

		annotation SummarizationSetBy = Automatic

	column 'Conversion rate'
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: be4ce0c5-513d-4a7a-a688-21db48611944
		summarizeBy: sum
		sourceColumn: conversion_rate

		annotation SummarizationSetBy = Automatic

	column z-statistic
		dataType: double
		formatString: 0.000
		lineageTag: 572a70bc-203f-4f6b-b70b-8de340655013
		summarizeBy: sum
		sourceColumn: z_stat

		annotation SummarizationSetBy = Automatic

	column p-value
		dataType: double
		formatString: 0.000
		lineageTag: eea10157-5cc0-4a52-bfb2-427e66609b35
		summarizeBy: sum
		sourceColumn: p_value

		annotation SummarizationSetBy = Automatic

	column 'Significant at 95%'
		dataType: int64
		formatString: 0
		lineageTag: ad33cb2e-390a-48e3-9c0f-f3304d234c66
		summarizeBy: sum
		sourceColumn: significativo_95

		annotation SummarizationSetBy = User

	partition ab_test_results = m
		mode: import
		source =
				let
				  Origen = Csv.Document(File.Contents("C:\Users\Nacho\Desktop\light-it-analytics\data\powerbi\ab_test_results.csv"), [Delimiter = ",", Columns = 8, QuoteStyle = QuoteStyle.None]),
				  #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"conversion_rate", type number}, {"z_stat", type number}, {"p_value", type number}}, "en-US"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Changed Type with Locale",{{"clicks", Int64.Type}, {"registros", Int64.Type}, {"significativo_95", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

