table monthly_channel_metrics
	lineageTag: d0923e9b-96e0-459f-9ce1-b93c670e5508

	measure 'Cost per signup (line)' = CALCULATE(SUM(monthly_channel_metrics[Cost per signup]), REMOVEFILTERS(monthly_channel_metrics[Month]))
		formatString: \$#,0
		lineageTag: 43b163f0-2623-442d-90ed-6b64b1c70304

	measure 'Cost per signup label' = VAR picked = CALCULATE(SELECTEDVALUE(monthly_channel_metrics[Month]), REMOVEFILTERS(months)) VAR axis = SELECTEDVALUE(months[Month]) VAR v = [Cost per signup (line)] RETURN IF(NOT ISBLANK(picked), IF(picked = axis, v), IF(CALCULATE(DISTINCTCOUNT(channels[Channel]), ALLSELECTED(channels[Channel])) = 1, v))
		formatString: \$#,0
		lineageTag: b87cf74a-da8d-412b-8ced-9d9781a8ddc1

	measure 'Signups label' = IF(CALCULATE(DISTINCTCOUNT(channels[Channel]), ALLSELECTED(channels[Channel])) = 1, SUM(monthly_channel_metrics[Signups]))
		formatString: 0
		lineageTag: 40924798-fd1a-46b1-87c2-e5d41f096947

	column channel_name
		dataType: string
		isHidden
		lineageTag: f4c61218-a763-447d-a580-ea4f8bdf1525
		summarizeBy: none
		sourceColumn: channel_name

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 60439772-3b17-4eaa-aa06-1ff6b1fda98b
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column Spend
		dataType: double
		formatString: \$#,0
		lineageTag: 846d6ab1-301f-4c1e-865b-7f661e479a54
		summarizeBy: sum
		sourceColumn: spend

		annotation SummarizationSetBy = Automatic

	column Signups
		dataType: int64
		formatString: 0
		lineageTag: c8d0cb90-bd0e-4ca5-b469-1923e4567868
		summarizeBy: sum
		sourceColumn: registros

		annotation SummarizationSetBy = Automatic

	column 'Cost per signup'
		dataType: double
		formatString: \$#,0.00
		lineageTag: 90444128-9dd9-4473-8dbf-72da82bc73e7
		summarizeBy: sum
		sourceColumn: costo_por_registro

		annotation SummarizationSetBy = Automatic

	partition monthly_channel_metrics = m
		mode: import
		source =
				let
				  Origen = Csv.Document(File.Contents("C:\Users\Nacho\Desktop\light-it-analytics\data\powerbi\monthly_channel_metrics.csv"), [Delimiter = ",", Columns = 5, QuoteStyle = QuoteStyle.None]),
				  #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"spend", type number}, {"costo_por_registro", type number}}, "en-US"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Changed Type with Locale",{{"registros", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

