table monthly_channel_metrics
	lineageTag: d0923e9b-96e0-459f-9ce1-b93c670e5508

	column channel_name
		dataType: string
		lineageTag: f4c61218-a763-447d-a580-ea4f8bdf1525
		summarizeBy: none
		sourceColumn: channel_name

		annotation SummarizationSetBy = Automatic

	column month
		dataType: string
		lineageTag: 60439772-3b17-4eaa-aa06-1ff6b1fda98b
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column spend
		dataType: double
		formatString: 0
		lineageTag: 846d6ab1-301f-4c1e-865b-7f661e479a54
		summarizeBy: sum
		sourceColumn: spend

		annotation SummarizationSetBy = Automatic

	column registros
		dataType: int64
		formatString: 0
		lineageTag: c8d0cb90-bd0e-4ca5-b469-1923e4567868
		summarizeBy: sum
		sourceColumn: registros

		annotation SummarizationSetBy = Automatic

	column costo_por_registro
		dataType: double
		formatString: 0
		lineageTag: 90444128-9dd9-4473-8dbf-72da82bc73e7
		summarizeBy: sum
		sourceColumn: costo_por_registro

		annotation SummarizationSetBy = Automatic

	partition monthly_channel_metrics = m
		mode: import
		source =
				let
				  Origen = Csv.Document(File.Contents("C:\Users\Nacho\Desktop\light-it-analytics\data\powerbi\monthly_channel_metrics.csv"), [Delimiter = ",", Columns = 5, QuoteStyle = QuoteStyle.None]),
				  #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"spend", type number}, {"costo_por_registro", type number}}, "en-US"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Changed Type with Locale",{{"registros", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

